name: Start Programming with Dart
type: dart # This should be either "dart" or "flutter".
steps:
  - name: Hello, World!
    directory: hello_world
    has_solution: false
  - name: Variables
    directory: variables
    has_solution: false
  - name: Types
    directory: types
    has_solution: false
  - name: Operators
    directory: operators
    has_solution: false
  - name: Compound Assignment Operators
    directory: compound_assignment_operators
    has_solution: false
  - name: Strings
    directory: strings
    has_solution: false 
  - name: Converting Temperatures
    directory: temperature
    has_solution: false
  - name: Making Decisions
    directory: making_decisions
    has_solution: false
  - name: Booleans
    directory: booleans
    has_solution: false
  - name: Boolean Expressions
    directory: boolean_expressions
    has_solution: false
  - name: Modulo Operator
    directory: modulo_operator
    has_solution: false
  - name: Switch
    directory: switch
    has_solution: false
  - name: Switching Grades
    directory: switching_grades
    has_solution: false
  - name: While Loops
    directory: while_loops
    has_solution: false
  - name: Do-While Loops
    directory: do_while_loops
    has_solution: false
  - name: For Loops
    directory: for_loops
    has_solution: false
  - name: Functions
    directory: functions
    has_solution: false
  - name: Function Parameters
    directory: function_parameters
    has_solution: false
  - name: More About Function Parameters
    directory: more_about_function_parameters
    has_solution: false
  - name: Function Return Values
    directory: function_return_values
    has_solution: false
  - name: Variable Scope
    directory: variable_scope
    has_solution: false
  - name: Examining Strings
    directory: examining_stringsexamining_strings
    has_solution: false