name: da_bootcamp
description: "Dart Academy Boot Camp"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: ^3.5.0

dependencies:
  awesome_flutter_extensions: ^1.2.0
  dart_mappable: ^4.2.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_smart_dialog: ^4.9.6+1
  go_router: ^14.2.6
  intl: ^0.19.0
  logging: ^1.2.0
  markdown_widget: ^2.3.2+6
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  tinycolor2: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  dart_mappable_builder: ^4.2.3
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/data/courses/courses.json
    - assets/data/courses/start_programming_with_dart/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
